"""The formula arm: the model writes expressions directly, to test whether STRUCTURE is a lever.

Khoa's tick, 2026-09-19: run both arms from one GPU session and measure, rather than argue.

WHY THIS ARM EXISTS (measured 2026-09-19, and it is the strongest fact on the table):
  - `OPERATORS.md` is the RC-85 allowlist: **85 usable operators**, anything else is a 400 reject.
  - Across **18,796** simulated USA formulas we have ever used **20** of them.
  - Of the 1,025 rows that reached the Sharpe bar, `ts_mean` appears in 100 %, `group_rank` in 100 %,
    `multiply` in 71 %. The whole book is three operators.
  - `forge/compose.py` can only ever produce two shapes -- `multiply(A+, B+)` and
    `if_else(greater(B+, 0.5), A, 0)`. Everything else it varies is fields, windows and settings.
So 65 operators and every non-trivial skeleton are unexplored, and the mechanism arm cannot reach
them by construction. Whether that unexplored space contains anything is UNKNOWN; this arm measures it.

WHAT THIS ARM GIVES UP, stated before any result: a bare expression has no economics to grade, so
the 8 hard gates of `fetched/hypothesis_standard.md` do not apply. That is exactly the gap that
separated the hand-written library (2.6-3.2 % of rows at the bar) from the random-within-grammar
generator (0.1 %, 0 platform passes in 920 sims). To keep some of it, each formula carries a
one-line rationale, and `check_rationale` refuses one that names no counterparty.

Output is a plan JSON for `forge/runner.py --plan`, the same path the C11 and POW experiments used,
so the live planner and the allocator are untouched. RULE 1: nothing here simulates.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
import time

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from forge import hypotheses as H  # noqa: E402
from forge import typed as TY  # noqa: E402
from forge.factory import DEFAULT_SETTINGS, MAX_OPS, candidate_id, op_count  # noqa: E402
from forge.llm import retrieve as RT  # noqa: E402
from forge.signature import signature  # noqa: E402

PLAN = ROOT / "state/forge/plans/llmformula.json"
ARM = "llmformula"
NEUTS = ("SUBINDUSTRY", "INDUSTRY", "STATISTICAL")
DECAYS = (0, 4, 8, 16)
BLOCK = re.compile(r"```(?:yaml)?[ \t]*formula[ \t]*\n(.*?)```", re.S | re.I)
THINK = re.compile(r"<(think|thinking|reasoning)>.*?</\1>", re.S | re.I)
WORD = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
GROUPS = ("sector", "industry", "subindustry", "market", "country")


def signatures(path=ROOT / "OPERATORS.md") -> dict:
    """{operator: its signature line}, read from OPERATORS.md's own headers.

    MEASURED 2026-09-19: 76 of the 85 allowlisted operators carry a signature line, and ALL of them
    together cost ~386 prompt tokens. That is why there is no vector store here -- the corpus that
    decides whether the model writes a legal call already fits in the prompt. Giving it 85 bare
    names and no argument lists is how it guesses `ts_regression(x, 20)` and earns a 400.
    """
    out = {}
    for m in re.finditer(r"^([a-z][a-z0-9_]*)\(([^\n]{0,120})\)\s*$", pathlib.Path(path).read_text(), re.M):
        out.setdefault(m.group(1), m.group(0).strip())
    return out


def allowlist(path=ROOT / "OPERATORS.md") -> set:
    """The RC-85 operators, read from the doc's own quick index so the two cannot drift."""
    ops = set()
    for line in pathlib.Path(path).read_text().splitlines():
        if not line.startswith("- **"):
            continue
        ops |= set(re.findall(r"`([a-z][a-z0-9_]*)`", line))
        if ops and not line.strip():
            break
    return ops


SYSTEM = """You write quantitative equity alpha EXPRESSIONS. Each one is a trade, not a formula
exercise: something a specific group of investors is getting wrong, expressed in operators.

You are being run because of a measured gap. Every alpha this desk has ever simulated -- 18,796 of
them -- used 20 of the 85 available operators, and the ones that worked are almost all the same
shape: group_rank(ts_mean(field, w), group), multiplied together. Repeating that shape is worthless;
it is already generated by the thousand. Your value is the shapes that generator CANNOT make.

HARD RULES. A machine checks each one before anything is simulated.
1. Every field id must be copied EXACTLY from the FIELDS table. Never invent one.
2. Every operator must come from the ALLOWLIST. Anything else is rejected by the platform.
3. Never divide or subtract across different units (a ratio minus a currency is meaningless).
   Rank-bound or zscore both operands before you multiply them.
4. A field whose cadence is quarterly or annual MUST be wrapped in ts_backfill(field, 63) or more.
5. Keep the whole expression under %d operators.
6. `rationale` is ONE sentence and must name WHO is on the other side of the trade -- retail
   investors, index funds, pension funds, mandate-driven institutions, market makers, dealers,
   short sellers, sell-side analysts. "The signal predicts returns" is not a rationale.

MAKE THE SHAPES DIFFERENT FROM EACH OTHER. Across your %d expressions, vary the skeleton, not just
the field. Things the existing generator can never produce, all legal here:
  - conditioning on a third quantity: trade_when(cond, alpha, -1), bucket(...), hump(x, 0.01)
  - within-group comparisons: group_zscore, group_mean, group_scale, group_neutralize, group_backfill
  - time structure: ts_regression, ts_corr, ts_std_dev, ts_arg_max, ts_entropy, ts_quantile, ts_step
  - event timing: days_from_last_change, last_diff_value, ts_delay, kth_element
  - shape: winsorize, normalize, quantile, sigmoid, tanh, log, sqrt, inverse, sign
A short expression on a rare field is worth more than a long one on a crowded field.

OUTPUT: exactly %d fenced blocks, nothing else, no commentary. One per expression:

```yaml formula
id: <snake_case_id, unique>
rationale: <one sentence naming the force AND who is on the other side>
formula: "<the expression>"
neutralization: <SUBINDUSTRY | INDUSTRY | STATISTICAL>
decay: <0 | 4 | 8 | 16>
```"""

TASK = """ALLOWLIST -- the only operators that exist, with their exact argument lists. An operator
called with the wrong arguments is rejected by the platform, so copy the shape you see here:
{ops}

GROUP arguments you may use: sector, industry, subindustry, market

FIELDS (dataset {dataset}, {region}, fewest users first -- uncrowded is the point):
{fields}

Write {n} expressions now, each a different shape. Only the fenced blocks."""

REPAIR = """The machine rejected some of your expressions. Each line is a fact about your output.
Rewrite ONLY the rejected ones, same format, nothing else.

{report}"""

AGENT_WORDS = H.AGENT_WORDS if hasattr(H, "AGENT_WORDS") else ("retail", "institution", "fund", "dealer",
                                                               "analyst", "market maker", "short seller")


def json_schema(n: int, fields: list) -> dict:
    """The envelope, as a vLLM `guided_json` schema: the reply CANNOT be malformed.

    Constrained decoding masks invalid tokens while sampling, so every failure expressible in the
    schema stops being a failure. Measured against what a 7B actually did here: "did not output the
    blocks" and "neutralization is not one of the three" become impossible; `fields` as an `enum`
    means it cannot even name a field that is not in front of it. What the schema CANNOT constrain
    is the expression text itself -- a balanced operator tree is beyond JSON schema -- which is what
    `formula_grammar` below is for.
    """
    ids = [f["id"] for f in fields]
    return {"type": "object", "required": ["items"], "additionalProperties": False,
            "properties": {"items": {
                "type": "array", "minItems": 1, "maxItems": n,
                "items": {"type": "object", "additionalProperties": False,
                          "required": ["id", "rationale", "formula", "fields_used", "neutralization", "decay"],
                          "properties": {
                              "id": {"type": "string", "pattern": "^[a-z][a-z0-9_]{2,48}$"},
                              "rationale": {"type": "string", "minLength": 40, "maxLength": 300},
                              "formula": {"type": "string", "minLength": 8, "maxLength": 600},
                              "fields_used": {"type": "array", "minItems": 1, "maxItems": 4,
                                              "items": {"type": "string", "enum": ids}},
                              "neutralization": {"type": "string", "enum": list(NEUTS)},
                              "decay": {"type": "integer", "enum": list(DECAYS)}}}}}}


def formula_grammar(fields: list, ops: set) -> str:
    """A GBNF grammar in which an invented field id or operator is UNREPRESENTABLE.

    `guided_json` cannot describe a balanced operator tree, so the expression stays free text under
    it. This grammar closes that: field ids and operator names are terminals drawn from the
    retrieved list and the RC-85 allowlist, so the sampler can only ever emit a legal call on a real
    field. It removes two of the six output checks by construction rather than catching them after.

    UNTESTED against a live server as of 2026-09-19 -- xgrammar's EBNF dialect is accepted by vLLM
    (`guided_grammar`), but nothing here has run against a GPU yet, so it is behind a flag and
    `guided_json` stays the default.
    """
    f = " | ".join('"%s"' % x["id"] for x in fields)
    o = " | ".join('"%s"' % x for x in sorted(ops))
    g = " | ".join('"%s"' % x for x in GROUPS)
    return ("root ::= expr\n"
            "expr ::= call | field | group | number\n"
            "call ::= op \"(\" expr (\", \" expr)* \")\"\n"
            "op ::= %s\n"
            "field ::= %s\n"
            "group ::= %s\n"
            "number ::= [0-9]+ (\".\" [0-9]+)?\n" % (o, f, g))


def parse_json_items(text: str) -> list:
    """Items out of a guided-JSON reply; falls back to the fenced-block parser for a free host."""
    try:
        d = json.loads(THINK.sub("", text or "").strip())
    except Exception:                                       # noqa: BLE001 -- untrusted model output
        return parse_formulas(text)
    items = d.get("items") if isinstance(d, dict) else d
    return [i for i in (items or []) if isinstance(i, dict) and i.get("formula") and i.get("id")]


def parse_formulas(text: str) -> list:
    """Every ```yaml formula block the model emitted, as dicts. Malformed blocks are dropped."""
    import yaml

    out = []
    for body in BLOCK.findall(THINK.sub("", text or "")):
        try:
            d = yaml.safe_load(body)
        except Exception:                                   # noqa: BLE001 -- untrusted model output
            continue
        if isinstance(d, dict) and d.get("formula") and d.get("id"):
            out.append(d)
    return out


def check_rationale(r: str) -> str:
    """'' when the sentence names a counterparty; otherwise why it does not."""
    low = (r or "").lower()
    if len(low.split()) < 8:
        return "rationale under 8 words"
    if not any(w in low for w in AGENT_WORDS):
        return "rationale names no counterparty (who is on the other side?)"
    return ""


def verify_formula(item: dict, ctx, ops: set) -> dict:
    """The checks a bare expression admits. Returns {ok, failed: [...], detail: '...'}."""
    f = str(item.get("formula") or "")
    bad = []

    used_ops = set(re.findall(r"([a-z_][a-z0-9_]*)\s*\(", f))
    off = sorted(used_ops - ops)
    if off:
        bad.append(("ops", "not on the RC-85 allowlist: %s" % ", ".join(off)))

    names = set(WORD.findall(f)) - used_ops - set(GROUPS) - {"true", "false", "filter"}
    unknown = sorted(n for n in names if n not in ctx.catalogue and not n.isdigit())
    if unknown:
        bad.append(("fields", "not a field at %s: %s" % (ctx.key, ", ".join(unknown[:4]))))

    if op_count(f) > MAX_OPS:
        bad.append(("size", "%d operators, the platform refuses over %d" % (op_count(f), MAX_OPS)))

    why = check_rationale(item.get("rationale", ""))
    if why:
        bad.append(("rationale", why))

    if item.get("neutralization") not in NEUTS:
        bad.append(("settings", "neutralization must be one of %s" % ", ".join(NEUTS)))
    if item.get("decay") not in DECAYS:
        bad.append(("settings", "decay must be one of %s" % ", ".join(str(d) for d in DECAYS)))

    if not any(k == "fields" for k, _ in bad):
        v = TY.judge(f, ctx.labels, region=ctx.key, structural=True)
        if not v.get("ok", True):
            bad.append(("typed", "; ".join(v.get("hard") or [str(v)])[:140]))

    return {"ok": not bad, "failed": [k for k, _ in bad],
            "detail": "; ".join("%s: %s" % kv for kv in bad), "id": item.get("id")}


def construction(item: dict, ctx, seed: int = 0) -> dict:
    """One plan entry, in the shape forge/runner.py --plan and the dispatcher expect."""
    f = item["formula"].strip()
    st = dict(DEFAULT_SETTINGS, region=ctx.region, delay=ctx.delay, universe=ctx.universe,
              neutralization=item["neutralization"], decay=int(item["decay"]), truncation=0.08)
    fd = {k: (v.get("id") if isinstance(v, dict) else v) for k, v in
          ((k, (ctx.catalogue[k].get("dataset") or {})) for k in ctx.catalogue)}
    sig = signature(f, ctx.region, ctx.delay, mechanism="llm:%s" % item["id"], field_datasets=fd)
    meta = {"forge": 1, "hypothesis": "llm:%s" % item["id"], "category": "LLM", "arm": ARM,
            "cand": candidate_id(f, st), "signature": sig["key"], "mechanism_key": sig["mechanism_key"],
            "dataset": "|".join(sig["datasets"]), "rationale": item.get("rationale", ""),
            "recipe": "LLMFORMULA", "seed": seed}
    return {"formula": f, "settings": st, "meta": meta}


def build_plan(items: list, ctx, out_path=PLAN, seed: int = 0) -> dict:
    cons = [construction(i, ctx, seed) for i in items]
    seen, uniq = set(), []
    for c in cons:                                          # two expressions can compile to one candidate
        if c["meta"]["cand"] in seen:
            continue
        seen.add(c["meta"]["cand"])
        uniq.append(c)
    plan = {"seed": seed, "n": len(uniq), "made_at": time.time(), "hypotheses": 1, "cells_considered": 1,
            "gate": {}, "blocks": [{"cell": "%s (LLM formulas)" % ctx.key, "weight": 0, "kept": len(uniq),
                                    "class": "LLMFORMULA"}],
            "quarantined": 0, "ensembles": "off", "n_ensembles": 0, "allocate": False, "pair_classes": {},
            "blocks_by_class": {"LLMFORMULA": len(uniq)}, "mode": "composites", "composites": 1,
            "n_composites": len(uniq), "by_delay": {0: 0, 1: len(uniq)}, "experiment": "LLMFORMULA",
            "constructions": uniq}
    pathlib.Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    pathlib.Path(out_path).write_text(json.dumps(plan))
    return plan


JSON_TAIL = """

RETURN JSON, nothing else: {{"items": [ ... {n} objects ... ]}}. Each object has exactly the keys
id, rationale, formula, fields_used, neutralization, decay. `fields_used` lists the field ids your
expression actually uses."""


def batch(ctx, model, dataset: str, n: int = 10, tries: int = 2, n_fields: int = 24,
          ops: set | None = None, guided: str = "json") -> list:
    """One call asks for `n` expressions; rejected ones get one repair round. Returns the keepers.

    Asking for many per call is the whole economy of this arm: the prompt (fields + allowlist) is
    ~4,000 tokens and an expression is ~120, so one call for ten is far cheaper than ten calls.

    `guided="json"` sends the schema, so the envelope and the settings cannot be sampled wrong;
    `"off"` falls back to fenced blocks for a host that has no constrained decoding.
    """
    ops = ops or allowlist()
    rows = RT.shortlist(ctx, dataset=dataset, n=n_fields)
    if not rows:
        return []
    sys_prompt = SYSTEM % (MAX_OPS, n, n)
    sigs = signatures()
    ops_block = "\n".join(sigs.get(o, o + "(...)") for o in sorted(ops))
    task = TASK.format(ops=ops_block, dataset=dataset, region=ctx.key, n=n,
                       fields=RT.fields_block(rows))
    schema = json_schema(n, rows) if guided == "json" else None
    if schema:
        task += JSON_TAIL.format(n=n)
    read = parse_json_items if schema else parse_formulas
    messages = [{"role": "system", "content": sys_prompt}, {"role": "user", "content": task}]
    kept, seen_ids = [], set()
    for _ in range(max(1, tries)):
        try:
            reply = model.chat(messages, schema=schema) if schema else model.chat(messages)
        except Exception:                                   # noqa: BLE001 -- transport failure ends this dataset
            break
        items = [i for i in read(reply) if i["id"] not in seen_ids]
        if not items:
            break
        report = []
        for it in items:
            seen_ids.add(it["id"])
            v = verify_formula(it, ctx, ops)
            if v["ok"]:
                kept.append(it)
            else:
                report.append("%s -- %s" % (it["id"], v["detail"]))
        if not report or len(kept) >= n:
            break
        messages += [{"role": "assistant", "content": reply},
                     {"role": "user", "content": REPAIR.format(report="\n".join(report[:10]))}]
    return kept


def main(argv=None) -> int:
    from forge.llm import author as A
    from forge.llm import verify as V

    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--model", default="Qwen/Qwen3.8-27B-FP8")
    ap.add_argument("--host", default="http://localhost:8000")
    ap.add_argument("--api", choices=("openai", "ollama"), default="openai")
    ap.add_argument("--api-key", default="")
    ap.add_argument("--datasets", default="", help="comma list; default = the least crowded signed datasets")
    ap.add_argument("--n", type=int, default=300, help="target number of expressions to keep")
    ap.add_argument("--per-call", type=int, default=10)
    ap.add_argument("--concurrency", type=int, default=16)
    ap.add_argument("--tries", type=int, default=2)
    ap.add_argument("--guided", choices=("json", "off"), default="json",
                    help="json = vLLM constrained decoding, so a malformed reply or an invalid "
                         "setting cannot be sampled at all; off = plain fenced blocks")
    ap.add_argument("--temperature", type=float, default=0.9, help="higher than the mechanism arm: shape diversity is the point")
    ap.add_argument("--out", default=str(PLAN))
    a = ap.parse_args(argv)

    ctx = V.Context()
    ops = allowlist()
    pool = ([d.strip() for d in a.datasets.split(",") if d.strip()] or
            [d["dataset"] for d in RT.datasets_for_author(ctx)])
    model = A.Model(a.model, a.host, a.temperature, api=a.api, api_key=a.api_key)
    rounds = max(1, -(-a.n // max(1, a.per_call)))
    jobs = [pool[i % len(pool)] for i in range(rounds)]
    print("%d operators on the allowlist; %d datasets in the pool; %d calls of %d"
          % (len(ops), len(pool), len(jobs), a.per_call))

    from concurrent import futures
    kept, t0 = [], time.time()
    with futures.ThreadPoolExecutor(max_workers=max(1, a.concurrency)) as pool_ex:
        futs = {pool_ex.submit(batch, ctx, model, ds, a.per_call, a.tries, 24, ops, a.guided): ds for ds in jobs}
        for fut in futures.as_completed(futs):
            try:
                got = fut.result()
            except Exception as exc:                        # noqa: BLE001
                print("  %-26s failed: %s" % (futs[fut], exc))
                continue
            kept += got
            print("  %-26s kept %2d  (running total %d)" % (futs[fut], len(got), len(kept)))

    plan = build_plan(kept[: a.n], ctx, a.out)
    print("\n%d expressions kept, %d distinct constructions -> %s  (%.0fs)"
          % (len(kept), plan["n"], a.out, time.time() - t0))
    return 0


if __name__ == "__main__":
    sys.exit(main())
